name: CI

on:
  # Run jobs on push to master or feature branches
  push:
    branches:
      - master
      - feature-*

  # Run any PRs.
  pull_request:

env:
  IMAGE_NAME: pi-gen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest
      
      - name: Build
        run: |
          ./build-docker.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: deploy/*.zip